### PR TITLE
Merge JSON sample into master

### PR DESCRIPTION
**Pull request by flrs-edf**
I think we should merge this branch into master, because it makes it easier for folks to find what we are working on. We should make clear in the readme that this is all still in development and thus nobody should expect master to be a "stable" version for now.
@stephenholleran @joejoeyjoseph @Dynorat what do you think?

### CODE REVIEW

**Comment by stephenholleran** [comment]
Yes, I agree.

Give me till tomorrow to just commit the updated json sample I currently working on and a notebook to read it and show simple tables.

**Comment by joejoeyjoseph** [comment]
I agree too. I will wait till @stephenholleran's green light to do so. Thanks!

**Comment by stephenholleran** [comment]
@joejoeyjoseph Feel free to merge this into master now.

**Comment by joejoeyjoseph** [comment]
@stephenholleran roger that!

**Pull request merged**
