### PR TITLE
update to version 1.0.0-2022-01

### PR DESCRIPTION
**Pull request by stephenholleran**

### CODE REVIEW

**Comment by abohara** [comment]
@stephenholleran @heikowestermann This is a large merge. I did a cursory look through and had these questions / concerns:

IEA WRA  Calibration feedback

- Getting an error loading the binder notebook. Are the links to Binder permanent ? Will they expire ?
- The link to `JSON Schema` seems to be failing in the digital calibration certification / readme.md
- The '/digital_calibration_certification/docs/readme.md' does not seem correct. For e.g. uncertainty is repeated a lot? , Lots of "Untitled object in IEA Wind TCP Task 43 Anemometer Calibration Certificate "
- In the Test item is there a way to tell `sensor_type` and `measurement_type` similar to IEA WRA model? How would some one infer what type of sensor / measurement_type` is being calibrated ? 
-

**Comment by heikowestermann** [comment]
@abohara @stephenholleran 
- I honestly don't know why the binder link fails. I would propose to remove the link, as github is perfectly fine to view the rendered notebook and loading binder takes ages. There is not really much interactive stuff going on, so a read-only variant is fine by me.
- I fixed the link in the README.md
- The docs are autogenerated by github-actions. As far as I know they are generated only on master or when triggered manually. I would suggest to wait for the merge and update the docs manually if the action is not triggered automatically.

**Comment by stephenholleran** [comment]
Thanks for reviewing @abohara !

@heikowestermann yeah, I think the binder cold be dropped. It is probably something to do with the paths but I'm sure something else will go wrong with it in a year or so. As you said, it is not that interactive and GitHub renders the notebook really well anyway.

**Comment by stephenholleran** [comment]
@abohara yes, a big merge. It is everything we have done for the last year. A good way to see what has changed is to check the contributing.md file as it lists everything.

I will update the version number to be 2022.01.

**Comment by abohara** [comment]
@stephenholleran @heikowestermann 

- Yes. Lets drop binder (@heikowestermann )

The standard data model uncertainty has `measurement_type` and `sensor_type` associated with each calibration result. The digital calibration does not. Is this intentional ?

Everything else looks good. Thanks for all the great work. Approving now and can review again if there are more changes.

**Review by abohara — APPROVED** [review]
Approving with the minor pending task of link removal to Binder.

**Pull request merged**
