### PR TITLE
Iss #36 account for remote sensing devices in the data model

### PR DESCRIPTION
**Pull request by stephenholleran**
Hi @kersting and @abohara,

I have finally made those changes we discussed at the last meeting.

I have also added in date_from and date_to to the lidar_config as the flow corrections could be turned on or off at any point during a measurement campaign.

I have also added a 'device_base_height' to account for either a sodar or lidar. If a lidar, the user can populate the 'window_height' and not worry about the 'device_base_height'.

Please could you both review and see what you think of these changes for remote sensing.

Thanks.

### CODE REVIEW

**Comment by stephenholleran** [comment]
Based on the conversation we had with Andy we should hold off on this pull request until we consolidate the terms.

**Comment by stephenholleran** [comment]
Hi @kersting and @abohara,

Happy new year!

I have finally made the updates to this pull request based on our chat with Andy Clifton before the holidays. 

I have used Task 32's 'datum plane' height instead of window or base of device height.
Added in lidar specific measurement types, units and statistic types.
Updated descriptions to include remote sensing and linked to Task 32 ontology in places.

Let me know if you have any comments. 

Thanks.

**Comment by kersting** [comment]
Happy new years!

Nice work! I've reviewed and I already merged.

**Review by kersting — COMMENTED** [review]
Quite big change. Everything looks good from my standpoint.

**Pull request merged**
