### PR TITLE
Add measurement location UUID field to the JSON Schema

### PR DESCRIPTION
**Pull request by jonssonchristian**
This PR provides the implementation for issue #232.

It includes the following additions:
- Add 'uuid' field under 'measurement_location' in the JSON Schema;
- Add example value for the  'uuid' field under 'measurement_location' in each of the three JSON file examples;
- Include the new 'uuid' field under 'measurement_location' when displaying data in 'load_demo_schema.ipynb'; and
- Expand the description of the field 'name' under 'measurement_location' to recommend selecting names that are expered to remain unique.

I have checked that all updated JSON examples validate successfully against the updated JSON Schema.

I tried to cover all the places that should be updated, but may have missed something. I did not add anything under the 'app' as I have the impression that creates the form dynamically from the content of the JSON Schema (but maybe I am wrong there). I did not update anything in the SQL files since they already include a 'uuid' field in the 'measurement_location' table.

I apologise I had not read the contributing guidelines properly before I created the branch, and missed that I should have tagged individual commits and the branch with the issue number. I will do that next time.

### CODE REVIEW

**Comment by stephenholleran** [comment]
Hi @christianjnaturalpower,

Just very quick comments, I haven't reviewed it fully.

The documentation files are all created automatically. Therefore no need to edit those. Could you remove those from this PR?

The create SQL statement file under Tools could also be updated to include this. See the contributing guidelines for the files to update: https://github.com/IEA-Task-43/digital_wra_data_standard/blob/master/contributing.md

And as I read it there myself, the CHANGELOG file too.

Cheers,

**Comment by christianjnaturalpower** [comment]
Thanks @stephenholleran.

> The documentation files are all created automatically. Therefore no need to edit those. Could you remove those from this PR?

I suspected that might be the case. I have removed the updates to the docs file now.

> The create SQL statement file under Tools could also be updated to include this. See the contributing guidelines for the files to update: https://github.com/IEA-Task-43/digital_wra_data_standard/blob/master/contributing.md

The file [iea43_wra_data_model_postgresql.sql](https://github.com/IEA-Task-43/digital_wra_data_standard/blob/master/tools/iea43_wra_data_model_postgresql.sql) already includes creating a `uuid` field in the `measurement_location` table. I could not see anywhere else where it would need to be updated. Let me know if I have missed something. I did not see any code that reads data from a JSON document and inserts it into the reference SQL database. If there is something like that I presume that also needs to be updated.

image

> And as I read it there myself, the CHANGELOG file too.

Updated.

**Comment by stephenholleran** [comment]
Hey @jonssonchristian,

We have agreed to do a new release with the changes we have made over the last year. I would like to include this one so your IEC group will have it. Please remind me if this is still good to go and I just have to review it or was there something else you were to do?

Cheers,

**Comment by jonssonchristian** [comment]
Hi @stephenholleran,

That sounds great. The PR includes everything I think needs to be updated to add the location `uuid` field. I pulled the latest version of the `dev` branch now and merged it into the branch for this PR.

**Review by stephenholleran — APPROVED** [review]
Hi @jonssonchristian,

I made some slight changes to the description text and updated the version in the demo files. Check those changes out and if you are ok with them, then I can merge it.

Cheers,

**Pull request merged**
