### PR TITLE
Iss #19 add height reference

### PR DESCRIPTION
**Pull request by stephenholleran**
Add the height reference to accommodate various references such as above ground level or above mean sea level.

### CODE REVIEW

**Comment by stephenholleran** [comment]
@kersting I tried to get @abohara as the reviewer as it was his suggestion in the first place but I can't seem to find him in the reviewers.

Could you take a look at this please?

**Comment by abohara** [comment]
@stephenholleran @kersting Do you see any scenarios where we would want to store multiple height reference ? Especially in offshore, height from mean sea level and high/low tide level ? Otherwise, I don't see any issues. We should probably set 'ground' as the default as it the most frequent use case (for now).

**Comment by stephenholleran** [comment]
@abohara 

>  Do you see any scenarios where we would want to store multiple height reference ?

I doubt it very much. 

> We should probably set 'ground' as the default as it the most frequent use case (for now).

Yep, done that already in the data model schema. Do you want it in the actual database create table statements too?

**Comment by kersting** [comment]
@stephenholleran  I see the new description for height but I had realized that height could also be -999 instead of null. Why do we need to accommodate -999? In which situation null would not be allowed?

**Comment by stephenholleran** [comment]
> In which situation null would not be allowed?

You're right. I'll take it out.

**Comment by stephenholleran** [comment]
@abohara and @kersting 

I have made those changes.  Are we good to go?

Thanks.

**Review by kersting — APPROVED** [review]

**Review by kersting — APPROVED** [review]

**Review by kersting — APPROVED** [review]

**Review by kersting — APPROVED** [review]

**Review by kersting — APPROVED** [review]

**Comment by kersting** [comment]
@stephenholleran It is all good. Thanks for the implementation.

**Pull request merged**
