### PR TITLE
iss #37 add mast geometry profiles to match IEC

### PR DESCRIPTION
**Pull request by stephenholleran**
Make the mast geometry to match those stated in the IEC.

### CODE REVIEW

**Comment by stephenholleran** [comment]
Hi @kersting , merge this if you are happy with it. You should then be able to merge this into your fork so you can start using it.

**Review by kersting — APPROVED** [review]

**Comment by kersting** [comment]
@stephenholleran I don't have write access to merge a pull request. Can you please give me access?

**Comment by stephenholleran** [comment]
> @stephenholleran I don't have write access to merge a pull request. Can you please give me access?

Are you able to now? If not I can make you an admin.

**Comment by kersting** [comment]
@stephenholleran Thanks! I just merged it.

**Pull request merged**
