### PR TITLE
Iss #159 implement floating lidar

### PR DESCRIPTION
**Pull request by stephenholleran**
Implementation of floating lidar specifics into the WRA Data Model.
Please see the discussion #148 and the issue log #159.

### CODE REVIEW

**Review by MatteoManaRWE — COMMENTED** [review]
it looks good to me !

**Comment by AdriaMiquelEOLOS** [comment]
Looks good to me as well. 
If I understood correctly, the only thing I miss for wave parameters is to have a generic 'wave_height', 'wave_period' and 'wave_direction' since there can be other parameters than 'wave_peak_period', 'wave_significant_height' and 'wave_average_direction'. Description of the parameter could be provided in the field "notes"

**Comment by stephenholleran** [comment]
Hi @AdriaMiquelEOLOS ,
Thanks for reviewing.
I'd say we can have generic parameters for those. We can discuss on the call later today.
Thanks.

**Comment by stephenholleran** [comment]
Hey @abohara,

If you get a chance could you please cast your eye over this pull request? Since the others reviewed I have added the generic 'wave_height' and 'wave_period' and updated the CHANGELOG to capture all the changes made for floating lidar. No breaking changes!

Thanks a mil,

Stephen

**Pull request merged**
