### PR TITLE
iss #215 add null to height_reference enum

### PR DESCRIPTION
**Pull request by stephenholleran**
Bug fix as highlighted in issue #215

### CODE REVIEW

**Comment by stephenholleran** [comment]
Hi @dancasey-ie,

I have fixed the bug you highlighted. Is this all good?

Thanks,

**Review by abohara — APPROVED** [review]
Looks good @stephenholleran . 

The postgres sql example , looks like it does not need to be edited to be compliant. Thanks.

**Comment by stephenholleran** [comment]
@abohara 

> looks like it does not need to be edited to be compliant.

No it doesn't as the create table statement doesn't have a 'NOT NULL' constraint so it can already accept nulls.

**Comment by dancasey-ie** [comment]
@stephenholleran yes looks correct.

**Pull request merged**
