### PR TITLE
Iss 260 add additional units

### PR DESCRIPTION
**Pull request by stephenholleran**
Issue #260 pull request which is adding units to the enum.

### CODE REVIEW

**Comment by stephenholleran** [comment]
Hi @heikowestermann and @NikoSimisiroglou,

Could you please review and approve (not to merge) this pull request?

It is just adding units to both the WRA Data Model and the Digital Calibration Certificate. See comments in issue #260.

Thanks,

**Comment by NikoSimisiroglou** [comment]
@stephenholleran  approved from my side.  I did not merge it as per your request. 

cc @heikowestermann

**Comment by heikowestermann** [comment]
@stephenholleran looks good!

**Review by heikowestermann — APPROVED** [review]
all good

**Pull request merged**
