### PR TITLE
lightning_finial_diameter

### PR DESCRIPTION
**Pull request by kersting**
Adding lighting finial diameter necessary for the IEC check. See the issue here. https://github.com/IEA-Task-43/digital_wra_data_standard/issues/156

### CODE REVIEW

**Comment by stephenholleran** [comment]
Hi @kersting, 

Thanks for implementing this. Regarding the flow of adding to the repo. What we usually do is create a branch off the 'dev' branch, do your work in there and then create a pull request to merge back into dev. Once we have sufficient enhancements to release we then merge dev into master while at the same time setting the new version number.

For this one it is not a big change so no need to go and create a branch for this.

I have a comment in the issue log for this that might change things slightly.

Cheers,

Stephen

**Comment by kersting** [comment]
@stephenholleran, I saw your comments and I can resubmit my pull request to dev if you want. Also, if you need support to review it, we can try to get help from Amit. Let me know how can I help.

**Comment by abohara** [comment]
@kersting @stephenholleran The lightning finial portion of this commit looks good. 

@stephenholleran I think the `contributing.md` describes the process well for future contributions.

**Comment by kersting** [comment]
@stephenholleran and @abohara I just made a commit to dev including the proposed modification proposed by @stephenholleran https://github.com/IEA-Task-43/digital_wra_data_standard/issues/156.

My proposal is for us to not proceed with this merge and just get all the ones from my commit in one batch including the latest addition from @stephenholleran. 

@abohara sorry but it was my mistake by making this pull request to early in the game.

**Comment by stephenholleran** [comment]
@kersting I am going to close this pull request as these are all already in the dev branch.

**Comment by kersting** [comment]
@stephenholleran thanks for closing and sorry for messing up twice.

**Review by kersting — COMMENTED** [review]
The new modifications look good to me.

**Pull request closed without merging**
